name = "Moving on up"
version = 3
copyright = "Biscotti"
author = "Biscotti"
description = "1 year anniversary edition. Each time you upgrade ACU you will hear a classic 90s tune. UI/Audio only mod."
url = "https://github.com/TakesTheBiscuit/faf_movingOnUP"
uid = "be7a2946-8bcc-11ea-bc55-0242ac140009"
icon = "/mods/faf_movingOnUP/icon.png"
exclusive = false
ui_only = true